In [1]:
import numpy as np
import pandas as pd

In [2]:
Laliga = pd.read_csv("C:/Users/Admin/Downloads/Laliga.csv")

In [3]:
Laliga = Laliga.replace('-',np.NaN)
Laliga

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,NaN,NaN,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,NaN,1,4,5,4,4,18,1939-40,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,NaN,2,3,4,4,14,1932-33,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,NaN,1,12,1941-42,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,NaN,NaN,NaN,2,4,5,11,1939-40,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,NaN,NaN,NaN,1,1,1,3,1948-49,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,NaN,1,1,2,NaN,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,NaN,1,1,2,2,1,7,1944-45,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,NaN,NaN,NaN,2,2,2,6,1935-36,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,NaN,NaN,NaN,1,NaN,1,2,1949-50,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,NaN,NaN,3,2,2,4,11,1933-34,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,NaN,NaN,2,NaN,2,1,5,1960-61,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,NaN,1,1,1,1,1,5,1951-52,2015-16,2
21,21,Villarreal,17,970,646,266,172,208,892,789,NaN,1,1,2,3,2,9,1998-99,2013-14,2
22,22,Granada,23,667,742,218,175,349,819,1157,NaN,NaN,NaN,NaN,NaN,2,2,1941-42,2016-17,6
23,23,Rayo Vallecano,17,662,652,189,148,305,760,1088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977-78,2015-16,8
24,24,Elche,21,606,678,203,180,295,750,1022,NaN,NaN,NaN,NaN,1,1,2,1959-60,2014-15,5
25,25,Getafe,12,553,456,147,112,197,520,633,NaN,NaN,NaN,NaN,NaN,1,1,2004-05,2015-16,6
26,26,Hercules,20,538,628,184,149,295,716,1050,NaN,NaN,NaN,NaN,1,4,5,1935-36,2010-11,5
27,27,Tenerife,13,510,494,155,128,211,619,744,NaN,NaN,NaN,NaN,2,NaN,2,1961-62,2009-10,5
28,28,Murcia,18,445,586,145,143,298,607,992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1940-41,2007-08,11
29,29,Alaves,12,421,380,125,81,174,458,623,NaN,NaN,NaN,NaN,NaN,1,1,1930-31,2016-17,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,32,Sabadell,14,353,426,129,95,202,492,720,NaN,NaN,NaN,1,1,NaN,2,1943-44,1987-88,4
33,33,Cadiz,12,343,448,104,127,217,393,662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977-78,2005-06,12
34,34,Logrones,9,293,346,96,92,158,291,489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1987-88,1996-97,7
35,35,Castellon,11,285,334,103,79,152,419,588,NaN,NaN,NaN,1,2,NaN,3,1941-42,1990-91,4
36,36,Albacete,7,277,270,76,76,118,320,410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1991-92,2004-05,7
37,37,Almeria,6,242,228,62,56,110,244,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08,2014-15,8
38,38,Cordoba,9,230,282,82,63,137,285,430,NaN,NaN,NaN,NaN,1,NaN,1,1962-63,2014-15,5
39,39,Compostela,4,190,160,52,45,63,199,241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994-95,1997-98,10
40,40,Recreativo,5,188,186,50,46,90,202,296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1978-79,2008-09,8
41,41,Burgos CF,6,168,204,59,50,95,216,310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1971-72,1979-80,12
42,42,Pontevedra,6,150,180,53,44,83,165,221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963-64,1969-70,7
43,43,Numancia,4,148,152,37,37,78,155,253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-00,2008-09,17
44,44,Eibar,3,132,114,35,27,52,139,167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-15,2014-15,10
45,45,Arenas,7,107,130,43,21,66,227,308,NaN,NaN,1,NaN,3,NaN,4,1929,1934-35,3
46,46,Real Burgos,3,96,114,26,44,44,101,139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990-91,1992-93,9
47,47,Gimnastic,4,91,116,34,16,66,181,295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947-48,2006-07,7
48,48,Extremadura,2,83,80,20,23,37,62,117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996-97,1998-99,17
49,49,Merida,2,81,80,19,24,37,70,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995-96,1997-98,19
50,50,Alcoyano,4,76,108,30,16,62,145,252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945-46,1950-51,10
51,51,Jaen,3,71,90,29,13,48,121,183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1953-54,1957-58,14
52,52,Real Union,4,56,72,21,14,37,153,184,NaN,NaN,NaN,NaN,NaN,1,1,1929,1931-32,6
53,53,AD Almeria,2,52,68,17,18,33,71,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1979-80,1980-81,10
54,54,Europa,3,42,54,18,6,30,97,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1929,1930-31,8
55,55,Lleida,2,40,68,13,14,41,70,182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1950-51,1993-94,16
56,56,Leganes,1,35,38,8,11,19,36,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-17,2016-17,17
57,57,Xerez,1,34,38,8,10,20,38,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-10,2009-10,20
58,58,Condal,1,22,30,7,8,15,37,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1956-57,1956-57,16
59,59,Atletico Tetuan,1,19,30,7,5,18,51,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1951-52,1951-52,16
60,60,Cultural Leonesa,1,14,30,5,4,21,34,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1955-56,1955-56,15
61,61,Girona,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-18,2017-18,9

In [4]:
Laliga = Laliga.fillna(0)
Laliga

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941-42,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939-40,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948-49,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944-45,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935-36,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949-50,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933-34,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960-61,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951-52,2015-16,2
21,21,Villarreal,17,970,646,266,172,208,892,789,0,1,1,2,3,2,9,1998-99,2013-14,2
22,22,Granada,23,667,742,218,175,349,819,1157,0,0,0,0,0,2,2,1941-42,2016-17,6
23,23,Rayo Vallecano,17,662,652,189,148,305,760,1088,0,0,0,0,0,0,0,1977-78,2015-16,8
24,24,Elche,21,606,678,203,180,295,750,1022,0,0,0,0,1,1,2,1959-60,2014-15,5
25,25,Getafe,12,553,456,147,112,197,520,633,0,0,0,0,0,1,1,2004-05,2015-16,6
26,26,Hercules,20,538,628,184,149,295,716,1050,0,0,0,0,1,4,5,1935-36,2010-11,5
27,27,Tenerife,13,510,494,155,128,211,619,744,0,0,0,0,2,0,2,1961-62,2009-10,5
28,28,Murcia,18,445,586,145,143,298,607,992,0,0,0,0,0,0,0,1940-41,2007-08,11
29,29,Alaves,12,421,380,125,81,174,458,623,0,0,0,0,0,1,1,1930-31,2016-17,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,32,Sabadell,14,353,426,129,95,202,492,720,0,0,0,1,1,0,2,1943-44,1987-88,4
33,33,Cadiz,12,343,448,104,127,217,393,662,0,0,0,0,0,0,0,1977-78,2005-06,12
34,34,Logrones,9,293,346,96,92,158,291,489,0,0,0,0,0,0,0,1987-88,1996-97,7
35,35,Castellon,11,285,334,103,79,152,419,588,0,0,0,1,2,0,3,1941-42,1990-91,4
36,36,Albacete,7,277,270,76,76,118,320,410,0,0,0,0,0,0,0,1991-92,2004-05,7
37,37,Almeria,6,242,228,62,56,110,244,366,0,0,0,0,0,0,0,2007-08,2014-15,8
38,38,Cordoba,9,230,282,82,63,137,285,430,0,0,0,0,1,0,1,1962-63,2014-15,5
39,39,Compostela,4,190,160,52,45,63,199,241,0,0,0,0,0,0,0,1994-95,1997-98,10
40,40,Recreativo,5,188,186,50,46,90,202,296,0,0,0,0,0,0,0,1978-79,2008-09,8
41,41,Burgos CF,6,168,204,59,50,95,216,310,0,0,0,0,0,0,0,1971-72,1979-80,12
42,42,Pontevedra,6,150,180,53,44,83,165,221,0,0,0,0,0,0,0,1963-64,1969-70,7
43,43,Numancia,4,148,152,37,37,78,155,253,0,0,0,0,0,0,0,1999-00,2008-09,17
44,44,Eibar,3,132,114,35,27,52,139,167,0,0,0,0,0,0,0,2014-15,2014-15,10
45,45,Arenas,7,107,130,43,21,66,227,308,0,0,1,0,3,0,4,1929,1934-35,3
46,46,Real Burgos,3,96,114,26,44,44,101,139,0,0,0,0,0,0,0,1990-91,1992-93,9
47,47,Gimnastic,4,91,116,34,16,66,181,295,0,0,0,0,0,0,0,1947-48,2006-07,7
48,48,Extremadura,2,83,80,20,23,37,62,117,0,0,0,0,0,0,0,1996-97,1998-99,17
49,49,Merida,2,81,80,19,24,37,70,115,0,0,0,0,0,0,0,1995-96,1997-98,19
50,50,Alcoyano,4,76,108,30,16,62,145,252,0,0,0,0,0,0,0,1945-46,1950-51,10
51,51,Jaen,3,71,90,29,13,48,121,183,0,0,0,0,0,0,0,1953-54,1957-58,14
52,52,Real Union,4,56,72,21,14,37,153,184,0,0,0,0,0,1,1,1929,1931-32,6
53,53,AD Almeria,2,52,68,17,18,33,71,116,0,0,0,0,0,0,0,1979-80,1980-81,10
54,54,Europa,3,42,54,18,6,30,97,131,0,0,0,0,0,0,0,1929,1930-31,8
55,55,Lleida,2,40,68,13,14,41,70,182,0,0,0,0,0,0,0,1950-51,1993-94,16
56,56,Leganes,1,35,38,8,11,19,36,55,0,0,0,0,0,0,0,2016-17,2016-17,17
57,57,Xerez,1,34,38,8,10,20,38,66,0,0,0,0,0,0,0,2009-10,2009-10,20
58,58,Condal,1,22,30,7,8,15,37,57,0,0,0,0,0,0,0,1956-57,1956-57,16
59,59,Atletico Tetuan,1,19,30,7,5,18,51,85,0,0,0,0,0,0,0,1951-52,1951-52,16
60,60,Cultural Leonesa,1,14,30,5,4,21,34,65,0,0,0,0,0,0,0,1955-56,1955-56,15
61,61,Girona,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2017-18,2017-18,9

In [6]:
Laliga.loc[((Laliga['Debut'] > '1929') & (Laliga['Debut'] < '1981'))]

KeyError: 'Debut'

In [ ]:
Laliga=